### PR TITLE
Fix wrong filenames for mesh sources

### LINKED ISSUE #14: mesh_edit_mesh.c and mesh_edit_mesh_fixup.c are named wrongly
https://github.com/recp/AssetKit/blob/35910c2c8e28a41c231acc17dd7d55e3b2791048/makefile.am#L145-L146

Should be mesh_edit_buff.c and mesh_edit_mesh_buff.c after [this refactor commit](https://github.com/recp/AssetKit/commit/2f6ead9bdbb8eebe4c81010ca1b7c6ee87a33bb8#diff-ecb4f2609a0632d06cad6f4e0e147b2f).

### PR DESCRIPTION
**Pull request by ningyuansg**
Resolves #14.

### CODE REVIEW

**Comment by recp** [comment]
Since I have started to work on **glTF**, I did not update the build files, so currently the build files are broken. I'm using Xcode to build libraries. Maybe I should share IDE's project files, maybe someone else could also use it. 

If we want to fix the build files then all build files must be updated.

**Comment by ningyuansg** [comment]
@recp Feel free to do so! Though, frankly—I don’t really understand what’s going on with the build. I don’t have much experience with compiled languages, so I’m really just pattern-matching here.

I stumbled upon this project while looking for a Wavefront OBJ to glTF/glb converter to embed in an android application of mine (therefore it would, preferably, need to be in C, C++, or Java). Now that I’ve had a look around, I don’t think this project is quite mature enough to do that (i may be wrong), so I unfortunately can’t justify spending anymore more time here.

(While I’m here, I don’t suppose you know where I can find such a converter? https://github.com/javagl/JglTF/tree/master/jgltf-obj is promising, but lacks the ability to parse colours in Wavefront’s MTL files.)

**Comment by recp** [comment]
In the future probably **AssetKit** will be best the option to convert Wavefront OBJ, glTF/glb and COLLADA... to each other. But currently it is in progress.

> (While I’m here, I don’t suppose you know where I can find such a converter?

Maybe you can use https://github.com/assimp/assimp for now.

I'll fix build asap and continue work on this project ...

**Comment by recp** [comment]
For glTF converters please see: https://github.com/KhronosGroup/glTF/#converters-importers-and-exporters

**Comment by recp** [comment]
@ningyuansg FWIW, the build with Autotools is fixed now which you can see on tracis-ci.

I'll fix it for Windows too asap.

**Comment by ningyuansg** [comment]
@recp Thanks for the links, I'll check them out!

**Pull request closed without merging**
